<?php
/** Workbench v9.12.0 — Workbench v9 Production Certification. */
if (!defined('ABSPATH')) { exit; }
function scwb_v9120_backend_request($path,$method='GET',$body=null){
    $base=defined('SCWB_BACKEND_URL')?rtrim(SCWB_BACKEND_URL,'/'):rtrim((string)get_option('scwb_backend_url','https://workbench-api.sustainablecatalyst.com'),'/');
    $args=array('method'=>$method,'timeout'=>120,'headers'=>array('Accept'=>'application/json','Content-Type'=>'application/json'));
    if($body!==null){$args['body']=wp_json_encode($body);} $r=wp_remote_request($base.$path,$args);
    if(is_wp_error($r)){return array('ok'=>false,'error'=>$r->get_error_message(),'_httpStatus'=>502);} $code=wp_remote_retrieve_response_code($r);$d=json_decode(wp_remote_retrieve_body($r),true);if(!is_array($d)){$d=array('ok'=>false,'error'=>'Invalid backend response');}$d['_httpStatus']=$code;return $d;
}
function scwb_v9120_status_shortcode(){ $r=scwb_v9120_backend_request('/v9120/status'); if(!empty($r['ok'])){return '<div class="scwb-v9120-status"><strong>Workbench v'.esc_html($r['version']).'</strong> · v9 Production Certification ready</div>';} return '<div class="scwb-v9120-status">v9 Production Certification unavailable</div>'; }
add_shortcode('sc_workbench_v9_production_certification_status','scwb_v9120_status_shortcode');
function scwb_v9120_certification_shortcode(){ $uid='scwb-v9120-'.wp_generate_uuid4();ob_start();?>
<div id="<?php echo esc_attr($uid); ?>" class="scwb-v9120" data-nonce="<?php echo esc_attr(wp_create_nonce('wp_rest')); ?>">
<style>.scwb-v9120{border:1px solid #d7d7d7;padding:20px;border-radius:12px;font-family:system-ui,sans-serif}.scwb-v9120 header{display:flex;justify-content:space-between;gap:16px;align-items:end;flex-wrap:wrap}.scwb-v9120 button{padding:9px 14px;margin:4px}.scwb-v9120 pre{max-height:680px;overflow:auto;background:#111;color:#d8ffd8;padding:12px;border-radius:8px}.scwb-v9120 label{display:block;margin:8px 0}.scwb-v9120 input,.scwb-v9120 textarea{width:100%;max-width:720px}</style>
<header><div><small>SUSTAINABLE CATALYST WORKBENCH · V9.12.0</small><h3>Workbench v9 Production Certification</h3><div>Audit runtime readiness and retained v9 research capabilities without certifying scientific validity.</div></div></header>
<label>Certification key <input data-f="certificationKey" value="workbench-v9-production"></label><label>Requested by <input data-f="requestedBy" value="wordpress"></label><label>Notes<textarea data-f="notes" rows="3"></textarea></label>
<div><button data-action="run" type="button">Run certification</button> <button data-action="save" type="button">Save certificate</button></div><p data-role="status">Ready</p><pre data-role="output">{}</pre>
<script>(()=>{const root=document.getElementById(<?php echo wp_json_encode($uid); ?>),q=s=>root.querySelector(s);const body=()=>({certificationKey:q('[data-f="certificationKey"]').value.trim(),requestedBy:q('[data-f="requestedBy"]').value.trim(),notes:q('[data-f="notes"]').value,includeStoreWriteProbe:true,includeCoreConfiguration:true,includeMilestoneManifestAudit:true});const api=async(path)=>{const r=await fetch(<?php echo wp_json_encode(rest_url('sc-workbench/v1/v9120')); ?>+path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-WP-Nonce':root.dataset.nonce},body:JSON.stringify(body())});return await r.json();};async function go(path){q('[data-role="status"]').textContent='Running certification…';try{const out=await api(path);q('[data-role="output"]').textContent=JSON.stringify(out,null,2);q('[data-role="status"]').textContent=out.ok?`PASS · ${out.summary?.passed||0}/${out.summary?.total||0} checks`:`FAIL · ${out.summary?.failed||0} checks failed`;}catch(e){q('[data-role="status"]').textContent=e.message;}}q('[data-action="run"]').onclick=()=>go('/run');q('[data-action="save"]').onclick=()=>go('/certifications');})();</script></div><?php return ob_get_clean();}
add_shortcode('sc_workbench_v9_production_certification','scwb_v9120_certification_shortcode');
add_action('rest_api_init',function(){ $perm=function(){return current_user_can('manage_options');};
    register_rest_route('sc-workbench/v1/v9120','/run',array('methods'=>'POST','permission_callback'=>$perm,'callback'=>function($r){$x=scwb_v9120_backend_request('/v9-production-certification/run','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));
    register_rest_route('sc-workbench/v1/v9120','/certifications',array('methods'=>'POST','permission_callback'=>$perm,'callback'=>function($r){$x=scwb_v9120_backend_request('/v9-production-certification/certifications','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));
});
