<?php
/** Workbench v8.11.0 — Research Publication & Evidence Handoff. */
if (!defined('ABSPATH')) { exit; }
function scwb_v8110_backend_request($path,$method='GET',$body=null){
    $base=defined('SCWB_BACKEND_URL')?rtrim(SCWB_BACKEND_URL,'/'):rtrim((string)get_option('scwb_backend_url','https://workbench-api.sustainablecatalyst.com'),'/');
    $args=array('method'=>$method,'timeout'=>30,'headers'=>array('Accept'=>'application/json','Content-Type'=>'application/json'));
    if($body!==null){$args['body']=wp_json_encode($body);} $r=wp_remote_request($base.$path,$args);
    if(is_wp_error($r)){return array('ok'=>false,'error'=>$r->get_error_message(),'_httpStatus'=>502);} $code=wp_remote_retrieve_response_code($r); $d=json_decode(wp_remote_retrieve_body($r),true); if(!is_array($d)){$d=array('ok'=>false,'error'=>'Invalid backend response');}$d['_httpStatus']=$code;return $d;
}
function scwb_v8110_status_shortcode(){ $r=scwb_v8110_backend_request('/v8110/status'); return '<pre class="scwb-v8110-status">'.esc_html(wp_json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>'; }
add_shortcode('sc_workbench_publication_evidence_handoff_status','scwb_v8110_status_shortcode');
function scwb_v8110_handoff_shortcode($atts=array()){
    $a=shortcode_atts(array('project'=>''),$atts);$project=sanitize_text_field($a['project']);$uid='scwb-v8110-'.wp_generate_uuid4();ob_start();?>
<div id="<?php echo esc_attr($uid); ?>" class="scwb-v8110" data-nonce="<?php echo esc_attr(wp_create_nonce('wp_rest')); ?>">
<style>.scwb-v8110{border:1px solid #d7d7d7;padding:20px;border-radius:12px;font-family:system-ui,sans-serif}.scwb-v8110 header{display:flex;justify-content:space-between;gap:16px;align-items:end;flex-wrap:wrap}.scwb-v8110 input,.scwb-v8110 textarea,.scwb-v8110 select{width:100%;box-sizing:border-box;padding:9px;margin:5px 0 12px}.scwb-v8110 button{padding:9px 14px;margin:4px}.scwb-v8110 .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.scwb-v8110 pre{max-height:520px;overflow:auto;background:#111;color:#d8ffd8;padding:12px;border-radius:8px}</style>
<header><div><small>SUSTAINABLE CATALYST WORKBENCH · V8.11.0</small><h3>Research Publication &amp; Evidence Handoff</h3><div>Package an immutable analysis snapshot for governed publication and cross-product handoff.</div></div><div><input data-role="project" value="<?php echo esc_attr($project); ?>" placeholder="project-key"><button data-action="load" type="button">Load snapshots</button></div></header>
<div class="grid"><label>Snapshot<select data-role="snapshot"><option value="">Choose snapshot</option></select></label><label>Publication type<select data-role="type"><option>report</option><option>article</option><option>working-paper</option><option>technical-note</option><option>research-note</option></select></label></div>
<label>Title<input data-role="title" placeholder="Publication title"></label><label>Abstract<textarea data-role="abstract" rows="4"></textarea></label><div class="grid"><label>Authors (one per line)<textarea data-role="authors" rows="4"></textarea></label><label>Keywords (one per line)<textarea data-role="keywords" rows="4"></textarea></label></div>
<label>Destinations<div><label><input type="checkbox" data-dest value="platform-core" checked> Platform Core</label> <label><input type="checkbox" data-dest value="knowledge-library" checked> Knowledge Library</label> <label><input type="checkbox" data-dest value="research-lab"> Research Lab</label> <label><input type="checkbox" data-dest value="external-publication"> External publication</label></div></label>
<div><button data-action="build" type="button">Build handoff</button><button data-action="save" type="button">Save immutable package</button><span data-role="status"></span></div><pre data-role="output">{}</pre>
<script>(()=>{const root=document.getElementById(<?php echo wp_json_encode($uid); ?>),q=s=>root.querySelector(s),qa=s=>[...root.querySelectorAll(s)];const api=async(path,method='GET',body=null)=>{const r=await fetch(<?php echo wp_json_encode(rest_url('sc-workbench/v1/v8110')); ?>+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-WP-Nonce':root.dataset.nonce},body:body?JSON.stringify(body):undefined});return await r.json();};const lines=r=>q(`[data-role="${r}"]`).value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const payload=()=>({projectKey:q('[data-role="project"]').value.trim(),snapshotHash:q('[data-role="snapshot"]').value,title:q('[data-role="title"]').value,abstract:q('[data-role="abstract"]').value,authors:lines('authors').map(name=>({name})),keywords:lines('keywords'),publicationType:q('[data-role="type"]').value,destinations:qa('[data-dest]:checked').map(x=>x.value),includeFigures:true,includeEvidenceManifest:true});q('[data-action="load"]').onclick=async()=>{const p=q('[data-role="project"]').value.trim();if(!p)return;q('[data-role="status"]').textContent='Loading…';const out=await api('/catalog?project='+encodeURIComponent(p));q('[data-role="snapshot"]').innerHTML='<option value="">Choose snapshot</option>'+(out.analysisSnapshots||[]).map(x=>`<option value="${x.snapshotHash}">${x.snapshotLabel||x.snapshotHash.slice(0,12)}</option>`).join('');q('[data-role="status"]').textContent=`Loaded ${out.analysisSnapshotCount||0} snapshots and ${out.handoffPackageCount||0} handoff packages.`;};q('[data-action="build"]').onclick=async()=>{q('[data-role="status"]').textContent='Building…';const out=await api('/build','POST',payload());q('[data-role="output"]').textContent=JSON.stringify(out,null,2);q('[data-role="status"]').textContent=out.ok?`Handoff ${out.packageHash?.slice(0,12)||''} built.`:(out.error||'Build failed');};q('[data-action="save"]').onclick=async()=>{q('[data-role="status"]').textContent='Saving…';const out=await api('/save','POST',{...payload(),packageLabel:q('[data-role="title"]').value||'Research publication & evidence handoff',createdBy:'wordpress'});q('[data-role="output"]').textContent=JSON.stringify(out,null,2);q('[data-role="status"]').textContent=out.ok?`Package ${out.packageHash?.slice(0,12)||''} saved.`:(out.error||'Save failed');};})();</script></div><?php return ob_get_clean();}
add_shortcode('sc_workbench_publication_evidence_handoff','scwb_v8110_handoff_shortcode');
add_action('rest_api_init',function(){register_rest_route('sc-workbench/v1/v8110','/catalog',array('methods'=>'GET','permission_callback'=>function(){return current_user_can('read');},'callback'=>function($r){$p=sanitize_text_field($r->get_param('project'));$x=scwb_v8110_backend_request('/publication-handoff/source-catalog/'.rawurlencode($p));$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));register_rest_route('sc-workbench/v1/v8110','/build',array('methods'=>'POST','permission_callback'=>function(){return current_user_can('read');},'callback'=>function($r){$x=scwb_v8110_backend_request('/publication-handoff/build','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));register_rest_route('sc-workbench/v1/v8110','/save',array('methods'=>'POST','permission_callback'=>function(){return current_user_can('edit_posts');},'callback'=>function($r){$x=scwb_v8110_backend_request('/publication-handoff/packages','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));});
