<?php
/** Workbench v9.0.0 — Unified Scientific Study Composer. */
if (!defined('ABSPATH')) { exit; }
function scwb_v900_backend_request($path,$method='GET',$body=null){
    $base=defined('SCWB_BACKEND_URL')?rtrim(SCWB_BACKEND_URL,'/'):rtrim((string)get_option('scwb_backend_url','https://workbench-api.sustainablecatalyst.com'),'/');
    $args=array('method'=>$method,'timeout'=>30,'headers'=>array('Accept'=>'application/json','Content-Type'=>'application/json'));
    if($body!==null){$args['body']=wp_json_encode($body);} $r=wp_remote_request($base.$path,$args);
    if(is_wp_error($r)){return array('ok'=>false,'error'=>$r->get_error_message(),'_httpStatus'=>502);} $code=wp_remote_retrieve_response_code($r);$d=json_decode(wp_remote_retrieve_body($r),true);if(!is_array($d)){$d=array('ok'=>false,'error'=>'Invalid backend response');}$d['_httpStatus']=$code;return $d;
}
function scwb_v900_status_shortcode(){ $r=scwb_v900_backend_request('/v900/status'); return '<pre class="scwb-v900-status">'.esc_html(wp_json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>'; }
add_shortcode('sc_workbench_scientific_study_composer_status','scwb_v900_status_shortcode');
function scwb_v900_study_shortcode($atts){
    $atts=shortcode_atts(array('project'=>''),$atts,'sc_workbench_scientific_study_composer'); $project=sanitize_text_field($atts['project']); $uid='scwb-v900-'.wp_generate_uuid4(); ob_start(); ?>
<div id="<?php echo esc_attr($uid); ?>" class="scwb-v900" data-project="<?php echo esc_attr($project); ?>" data-nonce="<?php echo esc_attr(wp_create_nonce('wp_rest')); ?>">
<style>.scwb-v900{border:1px solid #d7d7d7;padding:20px;border-radius:12px;font-family:system-ui,sans-serif}.scwb-v900 .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px}.scwb-v900 input,.scwb-v900 textarea,.scwb-v900 select{width:100%;box-sizing:border-box;padding:8px}.scwb-v900 button{padding:9px 14px;margin:8px 8px 8px 0}.scwb-v900 pre{max-height:560px;overflow:auto;background:#111;color:#d8ffd8;padding:12px;border-radius:8px}</style>
<small>SUSTAINABLE CATALYST WORKBENCH · V9.0.0</small><h3>Unified Scientific Study Composer</h3><div class="grid"><label>Project key<input data-f="projectKey" value="<?php echo esc_attr($project); ?>"></label><label>Study key<input data-f="studyKey" placeholder="study-001"></label><label>Title<input data-f="title"></label><label>Status<select data-f="status"><option>draft</option><option>active</option><option>analysis</option><option>publication</option><option>complete</option></select></label></div>
<label>Research question<textarea data-f="researchQuestion" rows="3"></textarea></label><div class="grid"><label>Design type<input data-f="designType" placeholder="observational, experiment, simulation…"></label><label>Methods (one per line)<textarea data-f="methods" rows="3"></textarea></label><label>Asset keys (one per line)<textarea data-f="assetKeys" rows="3"></textarea></label><label>Execution job IDs (one per line)<textarea data-f="executionJobIds" rows="3"></textarea></label><label>Analysis snapshot hash<input data-f="analysisSnapshotHash"></label><label>Publication package hash<input data-f="publicationPackageHash"></label></div>
<button data-action="compose" type="button">Compose study</button><button data-action="save" type="button">Save content-addressed study</button><span data-role="status"></span><pre data-role="output">{}</pre>
<script>(()=>{const root=document.getElementById(<?php echo wp_json_encode($uid); ?>),q=s=>root.querySelector(s),lines=n=>(q(`[data-f="${n}"]`).value||'').split(/\n/).map(x=>x.trim()).filter(Boolean);const body=()=>({projectKey:q('[data-f="projectKey"]').value.trim(),studyKey:q('[data-f="studyKey"]').value.trim(),title:q('[data-f="title"]').value.trim(),status:q('[data-f="status"]').value,researchQuestion:q('[data-f="researchQuestion"]').value.trim(),protocol:{designType:q('[data-f="designType"]').value.trim(),methods:lines('methods')},assetKeys:lines('assetKeys'),executionJobIds:lines('executionJobIds'),analysisSnapshotHash:q('[data-f="analysisSnapshotHash"]').value.trim(),publicationPackageHash:q('[data-f="publicationPackageHash"]').value.trim()});const api=async(path,method='POST',payload=null)=>{const r=await fetch(<?php echo wp_json_encode(rest_url('sc-workbench/v1/v900')); ?>+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-WP-Nonce':root.dataset.nonce},body:payload?JSON.stringify(payload):undefined});return await r.json();};const run=async(action)=>{q('[data-role="status"]').textContent='Working…';const payload=body();if(action==='save'){payload.createdBy='wordpress';payload.recordLabel='Unified scientific study';}const out=await api(action==='save'?'/studies':'/compose','POST',payload);q('[data-role="output"]').textContent=JSON.stringify(out,null,2);q('[data-role="status"]').textContent=out.ok?'Ready':'Error';};q('[data-action="compose"]').onclick=()=>run('compose');q('[data-action="save"]').onclick=()=>run('save');})();</script></div><?php return ob_get_clean();
}
add_shortcode('sc_workbench_scientific_study_composer','scwb_v900_study_shortcode');
add_action('rest_api_init',function(){
    $perm=function(){return current_user_can('edit_posts');};
    register_rest_route('sc-workbench/v1/v900','/compose',array('methods'=>'POST','permission_callback'=>$perm,'callback'=>function($r){$x=scwb_v900_backend_request('/study-composer/compose','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));
    register_rest_route('sc-workbench/v1/v900','/studies',array('methods'=>'POST','permission_callback'=>$perm,'callback'=>function($r){$x=scwb_v900_backend_request('/study-composer/studies','POST',$r->get_json_params());$st=intval($x['_httpStatus']??200);unset($x['_httpStatus']);return new WP_REST_Response($x,$st);}));
});
