from __future__ import annotations
from dataclasses import dataclass, asdict

@dataclass(frozen=True)
class ToolSpec:
    id: str
    title: str
    domain: str
    topic: str
    family: str
    engine: str
    description: str
    inputs: list[dict]
    graph_types: list[str]
    audience_modes: list[str]
    safety_level: str = "educational"


def input_field(name, label, kind="text", default="", help="", options=None):
    out = {"name": name, "label": label, "type": kind, "default": default, "help": help}
    if options:
        out["options"] = options
    return out

TOOLS: list[ToolSpec] = [
    ToolSpec("linear-system-solver", "Linear System Solver", "Mathematical Modeling", "Linear Algebra", "linear_algebra", "python/numpy", "Solve Ax=b, inspect rank, residual, condition number, determinant, eigenvalues, and stability warnings.", [input_field("A", "Matrix A", "textarea", "[[3,2],[1,2]]"), input_field("b", "Vector b", "text", "[5,5]")], ["residual_bar", "eigen_plot"], ["guided", "analyst", "expert"]),
    ToolSpec("calculus-function-analyzer", "Calculus Function Analyzer", "Mathematical Modeling", "Calculus", "calculus", "python/sympy-lite", "Analyze a single-variable function numerically: derivative, accumulation, slope, extrema scan, and sensitivity graph.", [input_field("expression", "Function f(x)", "text", "x**2 - 4*x + 3"), input_field("x_min", "x min", "number", "-5"), input_field("x_max", "x max", "number", "5")], ["function_curve", "derivative_curve"], ["guided", "analyst", "expert"]),
    ToolSpec("statistics-analyzer", "Statistics Analyzer", "Statistics", "Statistics", "statistics", "python/scipy + optional R", "Descriptive statistics, distribution shape, confidence interval, and histogram.", [input_field("data", "Data values", "textarea", "12,14,15,19,21,22,24,30")], ["histogram", "boxplot"], ["guided", "analyst", "expert"]),
    ToolSpec("regression-analyzer", "Regression Analyzer", "Statistics", "Regression", "statistics", "python/scipy + optional R", "Fit linear regression, estimate r-squared, p-values, residuals, and graph fit.", [input_field("x", "X values", "text", "1,2,3,4,5"), input_field("y", "Y values", "text", "2,4,5,4,7")], ["scatter_fit", "residuals"], ["guided", "analyst", "expert"]),
    ToolSpec("probability-distribution-calculator", "Probability Distribution Calculator", "Probability", "Probability", "probability", "python/scipy", "Normal, binomial, Poisson, and beta distribution probabilities with visualizations.", [input_field("distribution", "Distribution", "select", "normal", options=["normal", "binomial", "poisson", "beta"]), input_field("params", "Parameters", "text", "mean=0;sd=1"), input_field("value", "Value", "number", "1")], ["distribution_curve"], ["guided", "analyst", "expert"]),
    ToolSpec("differential-equation-simulator", "Differential Equation Simulator", "Mathematical Modeling", "Differential Equations", "differential_equations", "python/scipy + optional Julia", "Simulate exponential, logistic, oscillator, and predator-prey systems.", [input_field("model", "Model", "select", "logistic", options=["logistic", "exponential_decay", "harmonic_oscillator", "predator_prey"]), input_field("initial", "Initial state", "text", "10"), input_field("rate", "Rate", "number", "0.25"), input_field("t_end", "Time horizon", "number", "30")], ["trajectory"], ["guided", "analyst", "expert"]),
    ToolSpec("decision-analysis-tool", "Decision Analysis Tool", "Decision Science", "Decision Thinking", "decision", "python", "Weighted decision matrix, expected value, uncertainty, sensitivity, and regret.", [input_field("options", "Options", "textarea", "Option A,8,6,7\nOption B,6,9,8"), input_field("weights", "Weights", "text", "0.4,0.35,0.25")], ["score_bar", "sensitivity"], ["guided", "analyst", "expert"]),
    ToolSpec("economics-calculator", "Economics Calculator", "Economics", "Economic Systems", "economics", "python + optional R/Julia", "Supply-demand equilibrium, elasticity, NPV, break-even, multiplier, inequality, and input-output analysis.", [input_field("mode", "Mode", "select", "npv", options=["npv", "elasticity", "supply_demand", "break_even", "input_output", "inequality_gini"]), input_field("inputs", "Inputs", "textarea", "rate=0.08; cashflows=-1000,300,400,500")], ["curve", "bar", "lorenz"], ["guided", "analyst", "expert"]),
    ToolSpec("energy-systems-calculator", "Energy Systems Calculator", "Energy", "Energy Systems", "energy", "python + optional Julia/EnergyPlus", "Demand, cost, emissions, solar PV, battery autonomy, LCOE, building energy, and scenario curves.", [input_field("mode", "Mode", "select", "electricity_cost_emissions", options=["electricity_cost_emissions", "solar_pv", "battery_autonomy", "lcoe", "building_eui", "energy_mix"]), input_field("inputs", "Inputs", "textarea", "kwh=500;rate=0.16;kgco2_per_kwh=0.4")], ["load_curve", "scenario", "stacked"], ["guided", "analyst", "expert"]),
    ToolSpec("psychology-scale-analyzer", "Psychology Scale Analyzer", "Psychology", "Psychology and Grit", "psychology", "python + optional R", "Scale scoring, Cronbach alpha, item profile, grit/persistence curve, and intervention effect sizes.", [input_field("mode", "Mode", "select", "scale_reliability", options=["scale_reliability", "grit_profile", "effect_size", "memory_decay", "signal_detection"]), input_field("responses", "Responses / values", "textarea", "4,5,4,3\n3,4,4,2\n5,5,4,4")], ["boxplot", "profile", "curve"], ["guided", "analyst", "expert"]),
    ToolSpec("scientific-calculator", "Scientific Calculator", "Natural Science", "Physics, Chemistry, Biology", "science", "python + optional Julia", "Physics, chemistry, biology, astronomy, materials, and environmental calculations.", [input_field("mode", "Mode", "select", "ideal_gas", options=["ideal_gas", "kinetic_energy", "stress_strain", "dilution", "logistic_population", "orbital_period", "reynolds_number"]), input_field("inputs", "Inputs", "textarea", "n=1;R=8.314;T=298;V=0.024")], ["curve", "bar"], ["guided", "analyst", "expert"]),
    ToolSpec("engineering-calculator", "Engineering Calculator", "Engineering", "Engineering", "engineering", "python + optional C++", "Beam bending, shear/moment, truss basics, factor of safety, Reynolds number, voltage drop, and reliability.", [input_field("mode", "Mode", "select", "beam_uniform_load", options=["beam_uniform_load", "column_buckling", "factor_of_safety", "reynolds_number", "voltage_drop", "heat_transfer"]), input_field("inputs", "Inputs", "textarea", "span=6;load=10;E=200e9;I=8e-6")], ["shear_moment", "deflection"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("architecture-building-calculator", "Architecture & Building Calculator", "Architecture", "Built Environment", "architecture", "python + optional EnergyPlus/IfcOpenShell", "Space planning, occupancy, EUI, embodied carbon, solar orientation, daylight proxy, and adjacency matrices.", [input_field("mode", "Mode", "select", "space_program", options=["space_program", "occupancy_load", "building_eui", "embodied_carbon", "solar_shading", "adjacency_matrix"]), input_field("inputs", "Inputs", "textarea", "area_m2=1000;annual_kwh=180000")], ["program_bar", "carbon_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("sustainability-resilience-scorecard", "Sustainability & Resilience Scorecard", "Sustainability", "Risk & Resilience", "sustainability", "python", "Weighted resilience, exposure, sensitivity, adaptive capacity, governance, equity, and recovery diagnostics.", [input_field("scores", "Scores", "textarea", "exposure=4;sensitivity=3;adaptive_capacity=2;governance=3;equity=2;recovery=4")], ["radar_proxy", "bar"], ["guided", "analyst", "expert"]),
    ToolSpec("ai-governance-audit", "AI Governance Audit", "Governance", "AI Systems", "governance", "python + optional Haskell", "Risk, accountability, documentation, human oversight, dataset quality, transparency, and contestability audit.", [input_field("scores", "Scores", "textarea", "data_quality=3;transparency=2;human_oversight=4;contestability=2;impact=4")], ["risk_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("haskell-rule-checker", "Haskell Rule Checker", "Formal Logic", "Rules and Constraints", "formal_logic", "python + optional Haskell", "Constraint consistency checker for governance, ethics, engineering rules, and institutional logic.", [input_field("rules", "Rules", "textarea", "IF high_impact THEN human_review\nIF human_review THEN audit_log")], ["logic_trace"], ["analyst", "expert"]),
    ToolSpec("qualitative-interpretation-matrix", "Qualitative Interpretation Matrix", "Meaning", "Interpretation", "interpretation", "python + AI", "Structured interpretation for narrative, symbols, mythology, philosophy, ethics, culture, and institutions.", [input_field("text", "Text or case", "textarea", "Describe the case, symbol, narrative, or institution to interpret."), input_field("lens", "Lens", "select", "systems", options=["systems", "ethics", "symbolism", "narrative", "governance", "religion", "culture"] )], ["matrix"], ["guided", "analyst", "expert"]),

    ToolSpec("music-frequency-calculator", "Music Frequency Calculator", "Pattern, Geometry, Design, Music, and AI", "Music Theory", "music_pattern", "python/numpy", "Equal temperament, MIDI frequency, cents, harmonic series, beat frequency, and tempo timing analytics.", [input_field("mode", "Mode", "select", "midi_to_frequency", options=["midi_to_frequency", "equal_temperament", "cents_between", "tempo", "harmonic_series"]), input_field("midi", "MIDI note", "number", "69"), input_field("f0", "Base frequency", "number", "440"), input_field("f1", "Frequency 1", "number", "440"), input_field("f2", "Frequency 2", "number", "466.1638"), input_field("bpm", "Tempo BPM", "number", "120"), input_field("fundamental", "Fundamental Hz", "number", "110")], ["frequency_curve", "harmonic_bar", "tempo_grid"], ["guided", "analyst", "expert"]),
    ToolSpec("chord-scale-identifier", "Chord and Scale Identifier", "Pattern, Geometry, Design, Music, and AI", "Music Theory", "music_pattern", "python", "Identify pitch-class sets, common chords, scale candidates, and mode relationships.", [input_field("notes", "Notes or pitch classes", "text", "C E G")], ["pitch_class_bar"], ["guided", "analyst", "expert"]),
    ToolSpec("color-contrast-calculator", "Color Contrast and Luminance Calculator", "Pattern, Geometry, Design, Music, and AI", "Color Theory and Design", "color_design", "python", "HEX/RGB luminance, contrast ratio, accessibility checks, and color distance analytics.", [input_field("foreground", "Foreground HEX", "text", "#111111"), input_field("background", "Background HEX", "text", "#fff8e7")], ["luminance_bar", "contrast_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("color-harmony-generator", "Color Harmony Generator", "Pattern, Geometry, Design, Music, and AI", "Color Theory and Design", "color_design", "python", "Generate complementary, analogous, and triadic palettes with luminance profile.", [input_field("base", "Base HEX", "text", "#ff0000")], ["palette_luminance"], ["guided", "analyst", "expert"]),
    ToolSpec("vector-geometry-calculator", "Vector Geometry Calculator", "Pattern, Geometry, Design, Music, and AI", "Vector Geometry", "linear_algebra_geometry", "python/numpy", "Vector magnitude, dot product, angle, distance, projection, cross product, and transformation-ready geometry.", [input_field("mode", "Mode", "select", "dot_angle_projection", options=["dot_angle_projection", "projection", "cross_product"]), input_field("a", "Vector a", "text", "1,2,3"), input_field("b", "Vector b", "text", "4,5,6")], ["vector_plot", "component_bar"], ["guided", "analyst", "expert"]),
    ToolSpec("embedding-similarity-tool", "Embedding Similarity Tool", "Pattern, Geometry, Design, Music, and AI", "AI Representation", "ai_geometry", "python/numpy", "Cosine similarity, Euclidean distance, Manhattan distance, dot product, and embedding component comparison.", [input_field("a", "Embedding A", "textarea", "0.2,0.1,0.9,0.4"), input_field("b", "Embedding B", "textarea", "0.1,0.3,0.8,0.5")], ["component_line"], ["guided", "analyst", "expert"]),
    ToolSpec("pca-dimensionality-explorer", "PCA / Dimensionality Reduction Explorer", "Pattern, Geometry, Design, Music, and AI", "Mathematical Pattern", "dimensionality_reduction", "python/numpy", "SVD-based PCA, explained variance, component loadings, and score plots for pattern structure.", [input_field("data", "Data matrix", "textarea", "1,2,3\n2,3,4\n3,4,6\n4,5,8\n5,7,10")], ["explained_variance", "score_plot"], ["analyst", "expert"]),
    ToolSpec("fourier-frequency-analysis-tool", "Fourier / Frequency Analysis Tool", "Pattern, Geometry, Design, Music, and AI", "Mathematical Pattern", "frequency_analysis", "python/numpy", "Discrete Fourier spectrum for sound, signals, cyclical patterns, and frequency-domain reasoning.", [input_field("data", "Signal samples", "textarea", "0,1,0,-1,0,1,0,-1,0,1,0,-1"), input_field("sample_rate", "Sample rate", "number", "1")], ["frequency_spectrum"], ["analyst", "expert"]),
    ToolSpec("ai-classification-metrics-calculator", "AI Classification Metrics Calculator", "Pattern, Geometry, Design, Music, and AI", "AI Representation", "ai_evaluation", "python", "Accuracy, precision, recall, specificity, F1, and confusion-matrix visualization.", [input_field("tp", "True positives", "number", "50"), input_field("fp", "False positives", "number", "10"), input_field("tn", "True negatives", "number", "80"), input_field("fn", "False negatives", "number", "5")], ["metrics_bar", "confusion_matrix"], ["guided", "analyst", "expert"]),
    ToolSpec("multimodal-pattern-comparison-tool", "Multimodal Pattern Comparison Tool", "Pattern, Geometry, Design, Music, and AI", "Multimodal Analysis", "pattern_similarity", "python/numpy", "Compare numeric representations of visual, musical, textual, or design patterns using correlation and similarity metrics.", [input_field("pattern_a", "Pattern A", "textarea", "1,3,2,5,4,6"), input_field("pattern_b", "Pattern B", "textarea", "2,4,3,6,5,7")], ["pattern_line"], ["guided", "analyst", "expert"]),
    ToolSpec("environmental-monitoring-qaqc-tool", "Environmental Monitoring QA/QC Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Environmental Monitoring Systems", "environmental_monitoring", "python/numpy + optional R", "Sensor QA/QC, threshold exceedance, outlier detection, trend screening, data-quality flags, and monitoring visualizations.", [input_field("values", "Monitoring values", "textarea", "12,12.4,12.2,19.8,12.1,12.0,11.9"), input_field("lower_threshold", "Lower threshold", "number", "10"), input_field("upper_threshold", "Upper threshold", "number", "15"), input_field("z_limit", "Outlier z limit", "number", "3")], ["time_series", "threshold_flags"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("global-impact-assessment-matrix", "Global Impact Assessment Matrix", "Global Impact", "Public Systems and Global Risk", "impact_assessment", "python + AI", "Heavy multidomain impact matrix across climate, biodiversity, water, health, rights, economics, governance, equity, reversibility, and uncertainty.", [input_field("scores", "Impact scores", "textarea", "climate=4;biodiversity=4;water=3;public_health=4;human_rights=3;economic_disruption=3;governance=4;reversibility=2;uncertainty=4;equity=4"), input_field("weights", "Optional weights", "textarea", "")], ["impact_bar", "ranked_contributors"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("climate-change-scenario-tool", "Climate Change Scenario Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Climate Change", "climate_scenarios", "python + optional Julia", "Climate scenario proxy tool for warming pathways, carbon-budget framing, and sea-level proxy analysis with curves and uncertainty caveats.", [input_field("mode", "Mode", "select", "warming_pathway", options=["warming_pathway", "carbon_budget", "sea_level_proxy"]), input_field("inputs", "Inputs", "textarea", "baseline_temp=1.2;annual_change=0.025;years=80")], ["scenario_curve"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("earth-science-hazard-analyzer", "Earth Science Hazard Analyzer", "Earth, Ocean, Climate, and Environmental Monitoring", "Earth Science", "hazard_risk", "python + optional GIS", "Educational hazard-risk proxy using probability, exposure, vulnerability, adaptive capacity, and warning-time factors.", [input_field("inputs", "Inputs", "textarea", "probability=0.15;exposure=4;vulnerability=3;capacity=2;warning_time=1")], ["hazard_factor_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("marine-biology-ocean-health-tool", "Marine Biology and Ocean Health Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Marine Biology", "ocean_health", "python + optional R", "Ocean-health stress proxy using temperature anomaly, pH, dissolved oxygen, nutrients, plastic pressure, and biodiversity buffer.", [input_field("inputs", "Inputs", "textarea", "temperature_anomaly=1.4;ph=8.0;dissolved_oxygen=5.5;nutrients=3.0;plastic_index=2.0;biodiversity=3.5")], ["ocean_stress_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("astronomy-calculator", "Astronomy Calculator", "Natural Science", "Astronomy", "astronomy", "python/numpy", "Orbital period, escape velocity, luminosity-distance relation, and habitable-zone proxy calculations.", [input_field("mode", "Mode", "select", "orbital_period", options=["orbital_period", "escape_velocity", "luminosity_distance", "habitable_zone_proxy"]), input_field("inputs", "Inputs", "textarea", "central_mass=1.989e30;semi_major_axis=1.496e11")], ["bar", "units_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("materials-science-calculator", "Materials Science Calculator", "Natural Science", "Materials Science", "materials", "python + optional C++", "Stress-strain, diffusion length, thermal conduction, and fatigue-risk proxy tools with professional-review warning.", [input_field("mode", "Mode", "select", "stress_strain", options=["stress_strain", "diffusion", "thermal_conduction", "fatigue_proxy"]), input_field("inputs", "Inputs", "textarea", "force=1000;area=0.0005;delta_length=0.001;length=1")], ["stress_bar", "risk_summary"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("health-medical-public-health-tool", "Health and Medical/Public Health Analytics Tool", "Health and Medical", "Public Health and Medical Analytics", "public_health", "python + optional R", "Educational public-health analytics: incidence, relative risk, screening-test predictive values, and SIR proxy curves.", [input_field("mode", "Mode", "select", "public_health_risk", options=["public_health_risk", "relative_risk", "screening_test", "sir_proxy"]), input_field("inputs", "Inputs", "textarea", "population=100000;cases=250;sensitivity=0.9;specificity=0.95;prevalence=0.02")], ["risk_bar", "sir_curve"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("international-law-issue-mapper", "International Law Issue Mapper", "Global Governance", "International Law", "legal_issue_spotting", "python + AI", "Educational international-law issue mapper for jurisdiction, state responsibility, treaties, custom, human rights, environmental harm, remedies, evidence, and forums.", [input_field("case", "Case description", "textarea", "A cross-border environmental harm affects coastal communities and critical habitats.")], ["issue_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("legal-traditions-comparator", "Legal Traditions Comparator", "Global Governance", "Legal Traditions", "comparative_law", "python + qualitative framework", "Comparative legal-tradition matrix for common law, civil law, Islamic law, customary/indigenous law, religious traditions, socialist systems, and legal pluralism.", [input_field("traditions", "Traditions to compare", "text", "common law, civil law, islamic law")], ["comparison_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("metaphysics-framework-tool", "Metaphysics Framework Tool", "Meaning and Philosophy", "Metaphysics", "metaphysical_analysis", "python + AI", "Structured metaphysical inquiry for ontology, causation, time, identity, mind/matter, freedom, agency, and determinism.", [input_field("question", "Question or problem", "textarea", "What changes while something remains the same?"), input_field("lens", "Lens", "select", "ontology", options=["ontology", "causation", "time", "identity", "mind_matter", "freedom"])], ["conceptual_bar", "matrix"], ["guided", "analyst", "expert"]),

]

TOOL_BY_ID = {t.id: t for t in TOOLS}

def list_tools(domain: str | None = None, topic: str | None = None, limit: int | None = None) -> list[dict]:
    items = TOOLS
    if domain:
        d = domain.lower()
        items = [t for t in items if d in t.domain.lower()]
    if topic:
        q = topic.lower().replace('-', ' ')
        items = [t for t in items if q in (t.topic + ' ' + t.domain + ' ' + t.description + ' ' + t.family).lower()]
    data = [asdict(t) for t in items]
    if limit:
        data = data[:limit]
    return data

def get_tool(tool_id: str) -> dict | None:
    t = TOOL_BY_ID.get(tool_id)
    return asdict(t) if t else None

def search_tools(query: str, limit: int = 6) -> list[dict]:
    q = (query or '').lower()
    scored = []
    for t in TOOLS:
        blob = ' '.join([t.id, t.title, t.domain, t.topic, t.family, t.description, ' '.join(t.graph_types)]).lower()
        score = sum(2 if token in t.title.lower() else 1 for token in q.split() if token in blob)
        if score:
            scored.append((score, t))
    scored.sort(key=lambda x: (-x[0], x[1].title))
    return [asdict(t) for _, t in scored[:limit]] or [asdict(t) for t in TOOLS[:limit]]
