from __future__ import annotations
from dataclasses import dataclass, asdict

@dataclass(frozen=True)
class ToolSpec:
    id: str
    title: str
    domain: str
    topic: str
    family: str
    engine: str
    description: str
    inputs: list[dict]
    graph_types: list[str]
    audience_modes: list[str]
    safety_level: str = "educational"


def input_field(name, label, kind="text", default="", help="", options=None):
    out = {"name": name, "label": label, "type": kind, "default": default, "help": help}
    if options:
        out["options"] = options
    return out

TOOLS: list[ToolSpec] = [
    ToolSpec("linear-system-solver", "Linear System Solver", "Mathematical Modeling", "Linear Algebra", "linear_algebra", "python/numpy", "Solve Ax=b, inspect rank, residual, condition number, determinant, eigenvalues, and stability warnings.", [input_field("A", "Matrix A", "textarea", "[[3,2],[1,2]]"), input_field("b", "Vector b", "text", "[5,5]")], ["residual_bar", "eigen_plot"], ["guided", "analyst", "expert"]),
    ToolSpec("calculus-function-analyzer", "Calculus Function Analyzer", "Mathematical Modeling", "Calculus", "calculus", "python/sympy-lite", "Analyze a single-variable function numerically: derivative, accumulation, slope, extrema scan, and sensitivity graph.", [input_field("expression", "Function f(x)", "text", "x**2 - 4*x + 3"), input_field("x_min", "x min", "number", "-5"), input_field("x_max", "x max", "number", "5")], ["function_curve", "derivative_curve"], ["guided", "analyst", "expert"]),
    ToolSpec("statistics-analyzer", "Statistics Analyzer", "Statistics", "Statistics", "statistics", "python/scipy + optional R", "Descriptive statistics, distribution shape, confidence interval, and histogram.", [input_field("data", "Data values", "textarea", "12,14,15,19,21,22,24,30")], ["histogram", "boxplot"], ["guided", "analyst", "expert"]),
    ToolSpec("regression-analyzer", "Regression Analyzer", "Statistics", "Regression", "statistics", "python/scipy + optional R", "Fit linear regression, estimate r-squared, p-values, residuals, and graph fit.", [input_field("x", "X values", "text", "1,2,3,4,5"), input_field("y", "Y values", "text", "2,4,5,4,7")], ["scatter_fit", "residuals"], ["guided", "analyst", "expert"]),
    ToolSpec("probability-distribution-calculator", "Probability Distribution Calculator", "Probability", "Probability", "probability", "python/scipy", "Normal, binomial, Poisson, and beta distribution probabilities with visualizations.", [input_field("distribution", "Distribution", "select", "normal", options=["normal", "binomial", "poisson", "beta"]), input_field("params", "Parameters", "text", "mean=0;sd=1"), input_field("value", "Value", "number", "1")], ["distribution_curve"], ["guided", "analyst", "expert"]),
    ToolSpec("differential-equation-simulator", "Differential Equation Simulator", "Mathematical Modeling", "Differential Equations", "differential_equations", "python/scipy + optional Julia", "Simulate exponential, logistic, oscillator, and predator-prey systems.", [input_field("model", "Model", "select", "logistic", options=["logistic", "exponential_decay", "harmonic_oscillator", "predator_prey"]), input_field("initial", "Initial state", "text", "10"), input_field("rate", "Rate", "number", "0.25"), input_field("t_end", "Time horizon", "number", "30")], ["trajectory"], ["guided", "analyst", "expert"]),
    ToolSpec("decision-analysis-tool", "Decision Analysis Tool", "Decision Science", "Decision Thinking", "decision", "python", "Weighted decision matrix, expected value, uncertainty, sensitivity, and regret.", [input_field("options", "Options", "textarea", "Option A,8,6,7\nOption B,6,9,8"), input_field("weights", "Weights", "text", "0.4,0.35,0.25")], ["score_bar", "sensitivity"], ["guided", "analyst", "expert"]),
    ToolSpec("economics-calculator", "Economics Calculator", "Economics", "Economic Systems", "economics", "python + optional R/Julia", "Supply-demand equilibrium, elasticity, NPV, break-even, multiplier, inequality, and input-output analysis.", [input_field("mode", "Mode", "select", "npv", options=["npv", "elasticity", "supply_demand", "break_even", "input_output", "inequality_gini"]), input_field("inputs", "Inputs", "textarea", "rate=0.08; cashflows=-1000,300,400,500")], ["curve", "bar", "lorenz"], ["guided", "analyst", "expert"]),
    ToolSpec("energy-systems-calculator", "Energy Systems Calculator", "Energy", "Energy Systems", "energy", "python + optional Julia/EnergyPlus", "Demand, cost, emissions, solar PV, battery autonomy, LCOE, building energy, and scenario curves.", [input_field("mode", "Mode", "select", "electricity_cost_emissions", options=["electricity_cost_emissions", "solar_pv", "battery_autonomy", "lcoe", "building_eui", "energy_mix"]), input_field("inputs", "Inputs", "textarea", "kwh=500;rate=0.16;kgco2_per_kwh=0.4")], ["load_curve", "scenario", "stacked"], ["guided", "analyst", "expert"]),
    ToolSpec("psychology-scale-analyzer", "Psychology Scale Analyzer", "Psychology", "Psychology and Grit", "psychology", "python + optional R", "Scale scoring, Cronbach alpha, item profile, grit/persistence curve, and intervention effect sizes.", [input_field("mode", "Mode", "select", "scale_reliability", options=["scale_reliability", "grit_profile", "effect_size", "memory_decay", "signal_detection"]), input_field("responses", "Responses / values", "textarea", "4,5,4,3\n3,4,4,2\n5,5,4,4")], ["boxplot", "profile", "curve"], ["guided", "analyst", "expert"]),
    ToolSpec("scientific-calculator", "Scientific Calculator", "Natural Science", "Physics, Chemistry, Biology", "science", "python + optional Julia", "Physics, chemistry, biology, astronomy, materials, and environmental calculations.", [input_field("mode", "Mode", "select", "ideal_gas", options=["ideal_gas", "kinetic_energy", "stress_strain", "dilution", "logistic_population", "orbital_period", "reynolds_number"]), input_field("inputs", "Inputs", "textarea", "n=1;R=8.314;T=298;V=0.024")], ["curve", "bar"], ["guided", "analyst", "expert"]),
    ToolSpec("engineering-calculator", "Engineering Calculator", "Engineering", "Engineering", "engineering", "python + optional C++", "Beam bending, shear/moment, truss basics, factor of safety, Reynolds number, voltage drop, and reliability.", [input_field("mode", "Mode", "select", "beam_uniform_load", options=["beam_uniform_load", "column_buckling", "factor_of_safety", "reynolds_number", "voltage_drop", "heat_transfer"]), input_field("inputs", "Inputs", "textarea", "span=6;load=10;E=200e9;I=8e-6")], ["shear_moment", "deflection"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("architecture-building-calculator", "Architecture & Building Calculator", "Architecture", "Built Environment", "architecture", "python + optional EnergyPlus/IfcOpenShell", "Space planning, occupancy, EUI, embodied carbon, solar orientation, daylight proxy, and adjacency matrices.", [input_field("mode", "Mode", "select", "space_program", options=["space_program", "occupancy_load", "building_eui", "embodied_carbon", "solar_shading", "adjacency_matrix"]), input_field("inputs", "Inputs", "textarea", "area_m2=1000;annual_kwh=180000")], ["program_bar", "carbon_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("sustainability-resilience-scorecard", "Sustainability & Resilience Scorecard", "Sustainability", "Risk & Resilience", "sustainability", "python", "Weighted resilience, exposure, sensitivity, adaptive capacity, governance, equity, and recovery diagnostics.", [input_field("scores", "Scores", "textarea", "exposure=4;sensitivity=3;adaptive_capacity=2;governance=3;equity=2;recovery=4")], ["radar_proxy", "bar"], ["guided", "analyst", "expert"]),
    ToolSpec("ai-governance-audit", "AI Governance Audit", "Governance", "AI Systems", "governance", "python + optional Haskell", "Risk, accountability, documentation, human oversight, dataset quality, transparency, and contestability audit.", [input_field("scores", "Scores", "textarea", "data_quality=3;transparency=2;human_oversight=4;contestability=2;impact=4")], ["risk_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("haskell-rule-checker", "Haskell Rule Checker", "Formal Logic", "Rules and Constraints", "formal_logic", "python + optional Haskell", "Constraint consistency checker for governance, ethics, engineering rules, and institutional logic.", [input_field("rules", "Rules", "textarea", "IF high_impact THEN human_review\nIF human_review THEN audit_log")], ["logic_trace"], ["analyst", "expert"]),
    ToolSpec("qualitative-interpretation-matrix", "Qualitative Interpretation Matrix", "Meaning", "Interpretation", "interpretation", "python + AI", "Structured interpretation for narrative, symbols, mythology, philosophy, ethics, culture, and institutions.", [input_field("text", "Text or case", "textarea", "Describe the case, symbol, narrative, or institution to interpret."), input_field("lens", "Lens", "select", "systems", options=["systems", "ethics", "symbolism", "narrative", "governance", "religion", "culture"] )], ["matrix"], ["guided", "analyst", "expert"]),

    ToolSpec("music-frequency-calculator", "Music Frequency Calculator", "Pattern, Geometry, Design, Music, and AI", "Music Theory", "music_pattern", "python/numpy", "Equal temperament, MIDI frequency, cents, harmonic series, beat frequency, and tempo timing analytics.", [input_field("mode", "Mode", "select", "midi_to_frequency", options=["midi_to_frequency", "equal_temperament", "cents_between", "tempo", "harmonic_series"]), input_field("midi", "MIDI note", "number", "69"), input_field("f0", "Base frequency", "number", "440"), input_field("f1", "Frequency 1", "number", "440"), input_field("f2", "Frequency 2", "number", "466.1638"), input_field("bpm", "Tempo BPM", "number", "120"), input_field("fundamental", "Fundamental Hz", "number", "110")], ["frequency_curve", "harmonic_bar", "tempo_grid"], ["guided", "analyst", "expert"]),
    ToolSpec("chord-scale-identifier", "Chord and Scale Identifier", "Pattern, Geometry, Design, Music, and AI", "Music Theory", "music_pattern", "python", "Identify pitch-class sets, common chords, scale candidates, and mode relationships.", [input_field("notes", "Notes or pitch classes", "text", "C E G")], ["pitch_class_bar"], ["guided", "analyst", "expert"]),
    ToolSpec("color-contrast-calculator", "Color Contrast and Luminance Calculator", "Pattern, Geometry, Design, Music, and AI", "Color Theory and Design", "color_design", "python", "HEX/RGB luminance, contrast ratio, accessibility checks, and color distance analytics.", [input_field("foreground", "Foreground HEX", "text", "#111111"), input_field("background", "Background HEX", "text", "#fff8e7")], ["luminance_bar", "contrast_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("color-harmony-generator", "Color Harmony Generator", "Pattern, Geometry, Design, Music, and AI", "Color Theory and Design", "color_design", "python", "Generate complementary, analogous, and triadic palettes with luminance profile.", [input_field("base", "Base HEX", "text", "#ff0000")], ["palette_luminance"], ["guided", "analyst", "expert"]),
    ToolSpec("vector-geometry-calculator", "Vector Geometry Calculator", "Pattern, Geometry, Design, Music, and AI", "Vector Geometry", "linear_algebra_geometry", "python/numpy", "Vector magnitude, dot product, angle, distance, projection, cross product, and transformation-ready geometry.", [input_field("mode", "Mode", "select", "dot_angle_projection", options=["dot_angle_projection", "projection", "cross_product"]), input_field("a", "Vector a", "text", "1,2,3"), input_field("b", "Vector b", "text", "4,5,6")], ["vector_plot", "component_bar"], ["guided", "analyst", "expert"]),
    ToolSpec("embedding-similarity-tool", "Embedding Similarity Tool", "Pattern, Geometry, Design, Music, and AI", "AI Representation", "ai_geometry", "python/numpy", "Cosine similarity, Euclidean distance, Manhattan distance, dot product, and embedding component comparison.", [input_field("a", "Embedding A", "textarea", "0.2,0.1,0.9,0.4"), input_field("b", "Embedding B", "textarea", "0.1,0.3,0.8,0.5")], ["component_line"], ["guided", "analyst", "expert"]),
    ToolSpec("pca-dimensionality-explorer", "PCA / Dimensionality Reduction Explorer", "Pattern, Geometry, Design, Music, and AI", "Mathematical Pattern", "dimensionality_reduction", "python/numpy", "SVD-based PCA, explained variance, component loadings, and score plots for pattern structure.", [input_field("data", "Data matrix", "textarea", "1,2,3\n2,3,4\n3,4,6\n4,5,8\n5,7,10")], ["explained_variance", "score_plot"], ["analyst", "expert"]),
    ToolSpec("fourier-frequency-analysis-tool", "Fourier / Frequency Analysis Tool", "Pattern, Geometry, Design, Music, and AI", "Mathematical Pattern", "frequency_analysis", "python/numpy", "Discrete Fourier spectrum for sound, signals, cyclical patterns, and frequency-domain reasoning.", [input_field("data", "Signal samples", "textarea", "0,1,0,-1,0,1,0,-1,0,1,0,-1"), input_field("sample_rate", "Sample rate", "number", "1")], ["frequency_spectrum"], ["analyst", "expert"]),
    ToolSpec("ai-classification-metrics-calculator", "AI Classification Metrics Calculator", "Pattern, Geometry, Design, Music, and AI", "AI Representation", "ai_evaluation", "python", "Accuracy, precision, recall, specificity, F1, and confusion-matrix visualization.", [input_field("tp", "True positives", "number", "50"), input_field("fp", "False positives", "number", "10"), input_field("tn", "True negatives", "number", "80"), input_field("fn", "False negatives", "number", "5")], ["metrics_bar", "confusion_matrix"], ["guided", "analyst", "expert"]),
    ToolSpec("multimodal-pattern-comparison-tool", "Multimodal Pattern Comparison Tool", "Pattern, Geometry, Design, Music, and AI", "Multimodal Analysis", "pattern_similarity", "python/numpy", "Compare numeric representations of visual, musical, textual, or design patterns using correlation and similarity metrics.", [input_field("pattern_a", "Pattern A", "textarea", "1,3,2,5,4,6"), input_field("pattern_b", "Pattern B", "textarea", "2,4,3,6,5,7")], ["pattern_line"], ["guided", "analyst", "expert"]),
    ToolSpec("environmental-monitoring-qaqc-tool", "Environmental Monitoring QA/QC Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Environmental Monitoring Systems", "environmental_monitoring", "python/numpy + optional R", "Sensor QA/QC, threshold exceedance, outlier detection, trend screening, data-quality flags, and monitoring visualizations.", [input_field("values", "Monitoring values", "textarea", "12,12.4,12.2,19.8,12.1,12.0,11.9"), input_field("lower_threshold", "Lower threshold", "number", "10"), input_field("upper_threshold", "Upper threshold", "number", "15"), input_field("z_limit", "Outlier z limit", "number", "3")], ["time_series", "threshold_flags"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("global-impact-assessment-matrix", "Global Impact Assessment Matrix", "Global Impact", "Public Systems and Global Risk", "impact_assessment", "python + AI", "Heavy multidomain impact matrix across climate, biodiversity, water, health, rights, economics, governance, equity, reversibility, and uncertainty.", [input_field("scores", "Impact scores", "textarea", "climate=4;biodiversity=4;water=3;public_health=4;human_rights=3;economic_disruption=3;governance=4;reversibility=2;uncertainty=4;equity=4"), input_field("weights", "Optional weights", "textarea", "")], ["impact_bar", "ranked_contributors"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("climate-change-scenario-tool", "Climate Change Scenario Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Climate Change", "climate_scenarios", "python + optional Julia", "Climate scenario proxy tool for warming pathways, carbon-budget framing, and sea-level proxy analysis with curves and uncertainty caveats.", [input_field("mode", "Mode", "select", "warming_pathway", options=["warming_pathway", "carbon_budget", "sea_level_proxy"]), input_field("inputs", "Inputs", "textarea", "baseline_temp=1.2;annual_change=0.025;years=80")], ["scenario_curve"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("earth-science-hazard-analyzer", "Earth Science Hazard Analyzer", "Earth, Ocean, Climate, and Environmental Monitoring", "Earth Science", "hazard_risk", "python + optional GIS", "Educational hazard-risk proxy using probability, exposure, vulnerability, adaptive capacity, and warning-time factors.", [input_field("inputs", "Inputs", "textarea", "probability=0.15;exposure=4;vulnerability=3;capacity=2;warning_time=1")], ["hazard_factor_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("marine-biology-ocean-health-tool", "Marine Biology and Ocean Health Tool", "Earth, Ocean, Climate, and Environmental Monitoring", "Marine Biology", "ocean_health", "python + optional R", "Ocean-health stress proxy using temperature anomaly, pH, dissolved oxygen, nutrients, plastic pressure, and biodiversity buffer.", [input_field("inputs", "Inputs", "textarea", "temperature_anomaly=1.4;ph=8.0;dissolved_oxygen=5.5;nutrients=3.0;plastic_index=2.0;biodiversity=3.5")], ["ocean_stress_bar"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("astronomy-calculator", "Astronomy Calculator", "Natural Science", "Astronomy", "astronomy", "python/numpy", "Orbital period, escape velocity, luminosity-distance relation, and habitable-zone proxy calculations.", [input_field("mode", "Mode", "select", "orbital_period", options=["orbital_period", "escape_velocity", "luminosity_distance", "habitable_zone_proxy"]), input_field("inputs", "Inputs", "textarea", "central_mass=1.989e30;semi_major_axis=1.496e11")], ["bar", "units_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("materials-science-calculator", "Materials Science Calculator", "Natural Science", "Materials Science", "materials", "python + optional C++", "Stress-strain, diffusion length, thermal conduction, and fatigue-risk proxy tools with professional-review warning.", [input_field("mode", "Mode", "select", "stress_strain", options=["stress_strain", "diffusion", "thermal_conduction", "fatigue_proxy"]), input_field("inputs", "Inputs", "textarea", "force=1000;area=0.0005;delta_length=0.001;length=1")], ["stress_bar", "risk_summary"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("health-medical-public-health-tool", "Health and Medical/Public Health Analytics Tool", "Health and Medical", "Public Health and Medical Analytics", "public_health", "python + optional R", "Educational public-health analytics: incidence, relative risk, screening-test predictive values, and SIR proxy curves.", [input_field("mode", "Mode", "select", "public_health_risk", options=["public_health_risk", "relative_risk", "screening_test", "sir_proxy"]), input_field("inputs", "Inputs", "textarea", "population=100000;cases=250;sensitivity=0.9;specificity=0.95;prevalence=0.02")], ["risk_bar", "sir_curve"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("international-law-issue-mapper", "International Law Issue Mapper", "Global Governance", "International Law", "legal_issue_spotting", "python + AI", "Educational international-law issue mapper for jurisdiction, state responsibility, treaties, custom, human rights, environmental harm, remedies, evidence, and forums.", [input_field("case", "Case description", "textarea", "A cross-border environmental harm affects coastal communities and critical habitats.")], ["issue_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("legal-traditions-comparator", "Legal Traditions Comparator", "Global Governance", "Legal Traditions", "comparative_law", "python + qualitative framework", "Comparative legal-tradition matrix for common law, civil law, Islamic law, customary/indigenous law, religious traditions, socialist systems, and legal pluralism.", [input_field("traditions", "Traditions to compare", "text", "common law, civil law, islamic law")], ["comparison_bar", "matrix"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("metaphysics-framework-tool", "Metaphysics Framework Tool", "Meaning and Philosophy", "Metaphysics", "metaphysical_analysis", "python + AI", "Structured metaphysical inquiry for ontology, causation, time, identity, mind/matter, freedom, agency, and determinism.", [input_field("question", "Question or problem", "textarea", "What changes while something remains the same?"), input_field("lens", "Lens", "select", "ontology", options=["ontology", "causation", "time", "identity", "mind_matter", "freedom"])], ["conceptual_bar", "matrix"], ["guided", "analyst", "expert"]),
    ToolSpec("physics-calculator", "Physics Calculator", "Natural Science", "Physics", "physics", "python/numpy", "Mechanics, energy, waves, electricity, fluids, and thermodynamics calculations with unit-aware summaries and SVG graphs.", [input_field("mode", "Mode", "select", "mechanics", options=["mechanics", "energy_work", "waves", "electricity", "fluids", "thermodynamics"]), input_field("inputs", "Inputs", "textarea", "mass=2;velocity=12;height=5;force=10;distance=3;angle_deg=0")], ["curve", "bar", "units_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("chemistry-calculator", "Chemistry Calculator", "Natural Science", "Chemistry", "chemistry", "python", "Molarity, stoichiometry, pH, ideal gas, percent yield, and Beer-Lambert calculations for chemistry learning and analysis.", [input_field("mode", "Mode", "select", "molarity", options=["molarity", "stoichiometry", "ph", "ideal_gas", "percent_yield", "beer_lambert"]), input_field("inputs", "Inputs", "textarea", "moles=0.5;volume_l=1.0;mass_g=10;molar_mass_g_mol=58.44")], ["bar", "units_summary"], ["guided", "analyst", "expert"]),
    ToolSpec("biology-calculator", "Biology Calculator", "Natural Science", "Biology", "biology", "python/numpy", "Population growth, enzyme kinetics, Hardy-Weinberg proportions, biodiversity indexes, and photosynthesis proxy analysis.", [input_field("mode", "Mode", "select", "population_growth", options=["population_growth", "enzyme_kinetics", "hardy_weinberg", "biodiversity", "photosynthesis_proxy"]), input_field("inputs", "Inputs", "textarea", "initial=100;rate=0.25;carrying_capacity=1000;time=30")], ["curve", "bar"], ["guided", "analyst", "expert"]),
    ToolSpec("environmental-science-calculator", "Environmental Science Calculator", "Environmental Science", "Environmental Systems", "environmental_science", "python/numpy", "Water-quality, air-quality, carbon-footprint, habitat-fragmentation, and composite environmental-risk proxy calculations.", [input_field("mode", "Mode", "select", "water_quality_index", options=["water_quality_index", "air_quality_proxy", "carbon_footprint", "habitat_fragmentation", "environmental_risk_profile"]), input_field("inputs", "Inputs", "textarea", "do=7;ph=7.4;turbidity=3;nitrate=2;phosphate=0.1;temperature=18")], ["bar", "risk_profile"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("earth-science-calculator", "Earth Science Calculator", "Earth Science", "Earth Systems", "earth_science", "python/numpy", "Watershed runoff, earthquake energy proxy, erosion risk, rock density, and water-balance calculations.", [input_field("mode", "Mode", "select", "watershed_runoff", options=["watershed_runoff", "earthquake_energy", "erosion_risk", "rock_density", "water_balance"]), input_field("inputs", "Inputs", "textarea", "rainfall_mm=50;area_km2=10;runoff_coefficient=0.35;slope=8;soil_erodibility=0.3")], ["bar", "units_summary"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("content-frameworks-analyzer", "Content Frameworks Analyzer", "Content Frameworks", "Knowledge Architecture", "content_frameworks", "python + AI", "Maps briefs to purpose, audience, problem, evidence, structure, voice, action, ethics, and measurement dimensions.", [input_field("brief", "Brief or content problem", "textarea", "Explain a complex public-interest tool to a mixed audience and connect it to research, ethics, and action."), input_field("lens", "Lens", "select", "knowledge_architecture", options=["knowledge_architecture", "educational", "persuasive", "institutional", "measurement"] )], ["framework_bar", "matrix"], ["guided", "analyst", "expert"]),
    ToolSpec("storytelling-structure-analyzer", "Storytelling Structure Analyzer", "Content Frameworks", "Storytelling", "storytelling", "python + qualitative framework", "Analyzes narrative arc, stakes, conflict, character movement, resolution, and meaning without reducing story to formula.", [input_field("story", "Story, draft, or scenario", "textarea", "A researcher builds a public-interest tool, faces uncertainty, tests it with users, and turns it into shared infrastructure."), input_field("mode", "Mode", "select", "narrative_arc", options=["narrative_arc", "institutional_story", "ethical_story", "systems_story"] )], ["story_bar", "arc"], ["guided", "analyst", "expert"]),
    ToolSpec("social-psychology-analyzer", "Social Psychology Analyzer", "Psychology", "Social Psychology", "social_psychology", "python + qualitative framework", "Maps scenarios to norms, identity, trust, authority, conformity, cooperation, persuasion, polarization, and adoption mechanisms.", [input_field("scenario", "Scenario", "textarea", "A group is deciding whether to adopt a new tool while norms, trust, authority, incentives, and uncertainty shape behavior."), input_field("lens", "Lens", "select", "group_dynamics", options=["group_dynamics", "norms", "trust", "persuasion", "cooperation", "diffusion"] )], ["mechanism_bar", "matrix"], ["guided", "analyst", "expert"]),
    ToolSpec("grit-resilience-analyzer", "Grit and Resilience Analyzer", "Psychology", "Grit, Motivation, and Persistence", "grit_resilience", "python + optional R", "Reflective grit, persistence, recovery, deliberate-practice, and purpose-alignment profile with non-clinical caveats.", [input_field("responses", "Self-rating values", "textarea", "4,5,4,3,5,4,4,5"), input_field("context", "Context", "textarea", "Long-term learning, career transition, creative work, and sustained project execution.")], ["profile_bar", "reflection"], ["guided", "analyst", "expert"]),
    ToolSpec("nuclear-physics-calculator", "Nuclear Physics Calculator", "Advanced Physical Systems", "Nuclear Physics", "nuclear_physics", "python/numpy", "Radioactive decay, decay constants, binding energy, mean lifetime, and educational radiation-dose proxies with strict non-weapons safety boundaries.", [input_field("mode", "Mode", "select", "radioactive_decay", options=["radioactive_decay", "binding_energy", "radiation_dose_proxy", "mean_lifetime"]), input_field("inputs", "Inputs", "textarea", "initial_activity_bq=1000;half_life_s=3600;time_s=7200;mass_defect_u=0.01")], ["decay_curve", "bar", "pdf_report"], ["guided", "analyst", "expert"], "restricted_educational"),
    ToolSpec("particle-physics-calculator", "Particle Physics Calculator", "Advanced Physical Systems", "Particle Physics", "particle_physics", "python/numpy", "Relativistic energy/momentum, event-rate estimates, detector-resolution proxies, and lifetime-width relationships for educational high-energy physics.", [input_field("mode", "Mode", "select", "relativistic_energy_momentum", options=["relativistic_energy_momentum", "event_rate", "uncertainty_resolution", "lifetime_width"]), input_field("inputs", "Inputs", "textarea", "mass_mev_c2=0.511;momentum_mev_c=1;luminosity_cm2_s=1e34;cross_section_pb=1;time_s=3600")], ["energy_momentum_curve", "resolution_curve", "pdf_report"], ["guided", "analyst", "expert"], "restricted_educational"),
    ToolSpec("neurophysics-calculator", "Neurophysics Calculator", "Advanced Physical Systems", "Neurophysics and Biophysics", "neurophysics", "python/numpy", "Membrane RC time constants, Nernst potentials, integrate-and-fire proxies, and conduction delay for educational neurophysics.", [input_field("mode", "Mode", "select", "membrane_rc", options=["membrane_rc", "nernst_potential", "integrate_and_fire", "conduction_delay"]), input_field("inputs", "Inputs", "textarea", "resistance_mohm=100;capacitance_pf=100;temperature_c=37;z=1;outside_mm=145;inside_mm=15")], ["membrane_curve", "bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("rocket-science-calculator", "Rocket Science and Orbital Mechanics Calculator", "Engineering", "Aerospace and Rocket Science", "aerospace", "python/numpy", "Tsiolkovsky delta-v, thrust-to-weight, circular orbital velocity, period, and mass-ratio estimates for educational aerospace analysis.", [input_field("mode", "Mode", "select", "delta_v", options=["delta_v", "thrust_to_weight", "orbital_velocity", "mass_ratio_required"]), input_field("inputs", "Inputs", "textarea", "isp_s=300;initial_mass_kg=1000;final_mass_kg=500;thrust_n=15000;altitude_m=400000")], ["delta_v_curve", "bar", "pdf_report"], ["guided", "analyst", "expert"], "restricted_educational"),
    ToolSpec("electronics-engineering-calculator", "Electronics Engineering Calculator", "Engineering", "Electronics Engineering", "electronics", "python/numpy", "Ohm/power calculations, RC filters, RLC resonance, op-amp gain, ADC resolution, and circuit-summary graphs.", [input_field("mode", "Mode", "select", "ohms_law_power", options=["ohms_law_power", "rc_filter", "rlc_resonance", "op_amp_gain", "adc_resolution"]), input_field("inputs", "Inputs", "textarea", "voltage=12;resistance=100;capacitance_f=1e-6;frequency_hz=1000;inductance_h=0.01")], ["filter_response", "bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("rf-antenna-calculator", "RF and Antenna Calculator", "Engineering", "RF, Antenna, and Wireless Systems", "rf_antenna", "python/numpy", "Frequency/wavelength conversion, free-space path loss, Friis-style link budgets, antenna dimension estimates, and regulatory/safety caveats.", [input_field("mode", "Mode", "select", "wavelength_frequency", options=["wavelength_frequency", "free_space_path_loss", "link_budget", "antenna_gain"]), input_field("inputs", "Inputs", "textarea", "frequency_hz=915e6;distance_km=1;tx_power_dbm=20;tx_gain_dbi=2;rx_gain_dbi=2;losses_db=2")], ["path_loss_curve", "link_budget", "pdf_report"], ["guided", "analyst", "expert"], "restricted_educational"),
    ToolSpec("full-stack-engineering-tool", "Full-Stack Engineering Tool", "Engineering", "Engineering Systems", "engineering_stack", "python/numpy", "FMEA risk, factor of safety, reliability curves, systems-engineering maturity, and multidisciplinary engineering review support.", [input_field("mode", "Mode", "select", "fmea_risk", options=["fmea_risk", "factor_of_safety", "reliability", "systems_maturity"]), input_field("inputs", "Inputs", "textarea", "severity=4;occurrence=3;detection=2;load=1000;capacity=2500;mtbf_hours=10000;time_hours=1000")], ["risk_bar", "reliability_curve", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("lab-science-calculator", "Lab Science Calculator", "Lab Science", "Biology, Chemistry, and Laboratory QA/QC", "lab_science", "python/numpy", "Serial dilution, CFU counts, qPCR efficiency, dose-response research curves, replicate QA/QC, and lab-science calculations for biologists and chemists.", [input_field("mode", "Mode", "select", "serial_dilution", options=["serial_dilution", "cfu_count", "qpcr_efficiency", "dose_response_research", "replicate_qaqc"]), input_field("inputs", "Inputs", "textarea", "c1=1.0;v1_ml=1.0;v2_ml=10;od=0.8;dilution_factor=100;colony_count=80;plated_ml=0.1")], ["dose_response_curve", "bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("clinical-research-calculator", "Clinical Research Calculator", "Health and Medical", "Physician and Public-Health Research", "clinical_research", "python/numpy", "Diagnostic metrics, NNT, odds ratio, effect size, and clinical/public-health research calculations with non-diagnostic guardrails.", [input_field("mode", "Mode", "select", "diagnostic_metrics", options=["diagnostic_metrics", "nnt", "odds_ratio", "effect_size"]), input_field("inputs", "Inputs", "textarea", "tp=80;fp=10;tn=900;fn=20;event_rate_control=0.2;event_rate_treatment=0.12")], ["metrics_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),


    ToolSpec("predictive-analytics-forecasting-tool", "Predictive Analytics Forecasting Tool", "Predictive Analytics", "Forecasting and Decision Support", "forecasting", "python/numpy + optional R/Julia", "Moving average, exponential smoothing, linear trend forecasts, confidence proxies, forecast diagnostics, and downloadable graph/report outputs.", [input_field("mode", "Mode", "select", "linear_trend", options=["linear_trend", "moving_average", "exponential_smoothing"]), input_field("series", "Historical series", "textarea", "120,128,133,140,145,151,160,171,178,190,203,215"), input_field("horizon", "Forecast horizon", "number", "6"), input_field("alpha", "Smoothing alpha", "number", "0.35")], ["forecast_curve", "confidence_band", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("time-series-diagnostics-tool", "Time-Series Diagnostics Tool", "Predictive Analytics", "Time-Series Diagnostics", "time_series", "python/numpy + optional statsmodels", "Trend, rolling mean, volatility, autocorrelation, anomaly flags, and stationarity-warning proxies for monitoring and forecasting workflows.", [input_field("series", "Time series", "textarea", "10,11,13,12,15,18,17,21,24,23,26,30"), input_field("max_lag", "Max autocorrelation lag", "number", "8")], ["series_curve", "rolling_mean", "acf_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("economics-forecasting-scenario-tool", "Economics Forecasting and Scenario Tool", "Economics", "Economic Forecasting and Scenarios", "economic_forecasting", "python/numpy + optional R", "Macro scenario indices, demand forecasting, fiscal multiplier scenarios, cost-benefit streams, uncertainty framing, and policy-analysis outputs.", [input_field("mode", "Mode", "select", "macro_scenario", options=["macro_scenario", "demand_forecast", "fiscal_multiplier", "cost_benefit"]), input_field("inputs", "Inputs", "textarea", "gdp_growth=0.02;inflation=0.03;unemployment=0.05;policy_rate=0.04;demand=1000;price=10;elasticity=-1.2;shock=-0.1;multiplier=1.5")], ["scenario_curve", "demand_curve", "bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("econometrics-policy-model-tool", "Econometrics and Policy Model Tool", "Economics", "Econometrics and Policy Evaluation", "econometrics", "python/numpy + optional R", "OLS, elasticity regression, difference-in-differences decomposition, fitted values, residuals, and identification warnings for policy/economic analysis.", [input_field("mode", "Mode", "select", "ols", options=["ols", "elasticity_regression", "difference_in_differences"]), input_field("data", "Rows: predictors then outcome", "textarea", "1,2\n2,4\n3,5\n4,7\n5,8"), input_field("x", "X values", "text", "10,11,12,13,14,15"), input_field("y", "Y values", "text", "100,94,90,82,78,73"), input_field("inputs", "Policy contrast inputs", "textarea", "pre_treated=10;post_treated=16;pre_control=9;post_control=11")], ["fit_curve", "residuals", "did_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("fpga-digital-systems-tool", "FPGA and Digital Systems Tool", "Professional Systems Layer", "FPGA and Digital Design", "fpga", "python/numpy + HDL workflow adapters", "Timing slack, estimated Fmax, fixed-point range/quantization, pipeline throughput, resource pressure, and CDC-risk proxies for FPGA programmers.", [input_field("mode", "Mode", "select", "timing_slack", options=["timing_slack", "fixed_point", "pipeline_throughput", "resource_pressure"]), input_field("inputs", "Inputs", "textarea", "clock_mhz=100;critical_path_ns=7.5;lut_count=20000;bram_kb=1024;dsp_blocks=80;word_bits=16;pipeline_stages=4")], ["timing_bar", "resource_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("power-systems-engineering-tool", "Power Systems Engineering Tool", "Professional Systems Layer", "Electrical Power Engineering", "power_systems", "python/numpy", "Three-phase power, voltage drop, power-factor correction, transformer/loading, and fault-current proxy calculations for electrical engineers.", [input_field("mode", "Mode", "select", "three_phase_power", options=["three_phase_power", "voltage_drop", "power_factor_correction", "fault_current_proxy"]), input_field("inputs", "Inputs", "textarea", "voltage_v=480;current_a=100;power_factor=0.85;length_m=100;resistance_ohm_per_km=0.2;reactance_ohm_per_km=0.08")], ["power_bar", "load_curve", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("mechanical-systems-engineering-tool", "Mechanical Systems Engineering Tool", "Professional Systems Layer", "Mechanical Engineering", "mechanical_systems", "python/numpy", "Shaft torsion, vibration frequency, fatigue proxies, conduction heat transfer, and mechanical-system interpretation with professional caveats.", [input_field("mode", "Mode", "select", "shaft_torsion", options=["shaft_torsion", "vibration_frequency", "fatigue_proxy", "conduction_heat_transfer"]), input_field("inputs", "Inputs", "textarea", "torque_nm=500;radius_m=0.025;polar_j_m4=6.14e-7;length_m=1;shear_modulus_pa=79e9;mass_kg=10;stiffness_n_m=10000")], ["vibration_curve", "stress_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("structural-engineering-tool", "Structural Engineering Tool", "Professional Systems Layer", "Structural Engineering", "structural_engineering", "python/numpy", "Beam deflection, moment/shear proxies, Euler buckling, load combinations, and seismic base-shear proxy calculations with strict safety caveats.", [input_field("mode", "Mode", "select", "beam_deflection", options=["beam_deflection", "column_buckling", "load_combination", "seismic_base_shear_proxy"]), input_field("inputs", "Inputs", "textarea", "span_m=6;uniform_load_kn_m=10;E_pa=200e9;I_m4=8e-6;dead_load=100;live_load=75;wind_load=40")], ["moment_curve", "load_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("civil-infrastructure-planning-tool", "Civil Infrastructure Planning Tool", "Professional Systems Layer", "Civil Infrastructure", "civil_infrastructure", "python/numpy", "Stormwater storage, water demand, capacity utilization, asset-risk priority, and infrastructure planning metrics.", [input_field("mode", "Mode", "select", "stormwater_storage", options=["stormwater_storage", "water_demand", "capacity_utilization", "asset_condition_risk"]), input_field("inputs", "Inputs", "textarea", "area_ha=2;rainfall_mm=50;runoff_coefficient=0.7;population=10000;daily_l_per_capita=180;capacity=12000;demand=9000")], ["risk_bar", "capacity_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("urban-planning-analytics-tool", "Urban Planning Analytics Tool", "Professional Systems Layer", "Urban Planning", "urban_planning", "python/numpy + GIS-ready", "Density, jobs-housing balance, land-use mix entropy, housing affordability, accessibility proxies, and planning-equity caveats.", [input_field("mode", "Mode", "select", "land_use_mix", options=["land_use_mix", "density_access", "housing_affordability"]), input_field("inputs", "Inputs", "textarea", "population=50000;area_km2=12;jobs=25000;housing_units=22000;income=65000;housing_cost_monthly=1600;residential=0.45;commercial=0.25;industrial=0.1;civic=0.1;open_space=0.1")], ["land_use_bar", "density_table", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("architecture-building-science-tool", "Architecture and Building Science Tool", "Professional Systems Layer", "Architecture and Building Science", "building_science", "python/numpy + EnergyPlus/IFC-ready", "HVAC load proxies, daylight ratios, egress/occupancy metrics, envelope performance, embodied carbon, and building-science reports.", [input_field("mode", "Mode", "select", "hvac_load_proxy", options=["hvac_load_proxy", "egress_occupancy", "daylight_proxy", "embodied_carbon"]), input_field("inputs", "Inputs", "textarea", "area_m2=1000;u_value=0.35;delta_t_k=20;window_area_m2=150;shgc=0.35;solar_w_m2=500;occupants=120;floor_area_m2=1000")], ["building_load_bar", "daylight_bar", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("astrophysics-research-calculator", "Astrophysics Research Calculator", "Professional Systems Layer", "Astrophysics and Space Science", "astrophysics", "python/numpy", "Blackbody spectra, luminosity, low-redshift Hubble estimates, Kepler orbital periods, and astrophysical research calculators.", [input_field("mode", "Mode", "select", "blackbody", options=["blackbody", "luminosity", "redshift_hubble", "kepler_orbit"]), input_field("inputs", "Inputs", "textarea", "temperature_k=5778;radius_m=6.957e8;redshift=0.05;period_days=365.25;semi_major_axis_au=1")], ["spectrum_curve", "orbital_summary", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),


    ToolSpec("cognitive-psychology-tool", "Cognitive Psychology Tool", "Psychology", "Cognitive Psychology", "cognitive_psychology", "python/numpy", "Attention, working memory, mental models, cognitive load, and transfer analysis.", [input_field("scores", "Dimension scores", "textarea", "attention=4;working_memory=3;mental_models=4;cognitive_load=2;transfer=3")], ["profile_bar", "pdf_report"], ["guided", "analyst", "expert"]),
    ToolSpec("developmental-psychology-tool", "Developmental Psychology Tool", "Psychology", "Developmental Psychology", "developmental_psychology", "python/numpy", "Developmental dimensions across cognition, social development, language, emotion regulation, and context support.", [input_field("scores", "Dimension scores", "textarea", "cognitive_development=3;social_development=4;language=3;emotion_regulation=3;context_support=4")], ["profile_bar"], ["guided", "analyst", "expert"]),
    ToolSpec("personality-psychology-tool", "Personality Psychology Tool", "Psychology", "Personality Psychology", "personality_psychology", "python/numpy", "Big-Five-style reflective personality profile for education and self-analysis.", [input_field("scores", "Trait scores", "textarea", "openness=4;conscientiousness=4;extraversion=3;agreeableness=4;emotional_stability=3")], ["trait_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("positive-psychology-tool", "Positive Psychology Tool", "Psychology", "Positive Psychology", "positive_psychology", "python/numpy", "PERMA-style wellbeing, strengths, meaning, engagement, relationships, and accomplishment profile.", [input_field("scores", "Dimension scores", "textarea", "meaning=4;engagement=3;relationships=4;accomplishment=3;positive_emotion=3;strengths_use=4")], ["wellbeing_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("organizational-psychology-tool", "Organizational Psychology Tool", "Psychology", "Organizational Psychology", "organizational_psychology", "python/numpy", "Role clarity, psychological safety, motivation, coordination, feedback, and burnout-risk review.", [input_field("scores", "Dimension scores", "textarea", "role_clarity=3;psychological_safety=3;motivation=4;coordination=3;feedback=2;burnout_risk_inverse=3")], ["organization_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("institutional-psychology-tool", "Institutional Psychology Tool", "Psychology", "Institutional Psychology", "institutional_psychology", "python/numpy", "Trust, legitimacy, norms, accountability, institutional learning, and symbolic coherence.", [input_field("scores", "Dimension scores", "textarea", "trust=3;legitimacy=3;norm_clarity=3;accountability=3;learning_capacity=3;symbolic_coherence=3")], ["institution_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("analytical-psychology-symbolism-tool", "Analytical Psychology, Symbolism, and Depth Mind Tool", "Psychology", "Analytical Psychology, Symbolism & the Depth Mind", "analytical_psychology", "python/numpy + AI-ready", "Symbolic, archetypal, shadow, integration, and narrative-depth analysis for stories, myths, images, and institutions.", [input_field("scores", "Dimension scores", "textarea", "symbol_density=4;archetypal_pattern=4;shadow_tension=3;integration_potential=3;narrative_depth=4")], ["symbol_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("behavioral-science-psychology-hub-tool", "Behavioral Science and Psychology Hub Tool", "Behavioral Science & Psychology", "Behavioral Science & Psychology Hub", "behavioral_science", "python/numpy", "Behavior definition, context mapping, measurement, intervention fit, ethics, and evaluation.", [input_field("scores", "Dimension scores", "textarea", "behavior_definition=4;context_mapping=3;measurement=3;intervention_fit=3;ethics=4;evaluation=3")], ["behavior_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("behavioral-economics-tool", "Behavioral Economics Tool", "Behavioral Science & Psychology", "Behavioral Economics", "behavioral_economics", "python/numpy", "Loss aversion, present bias, framing, status quo bias, social proof, and choice friction.", [input_field("scores", "Dimension scores", "textarea", "loss_aversion=3;present_bias=4;status_quo_bias=3;framing_effect=4;social_proof=3;choice_friction=2")], ["bias_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("behavior-change-habit-tool", "Behavior Change and Habit Formation Tool", "Behavioral Science & Psychology", "Behavior Change and Habit Formation", "behavior_change", "python/numpy", "Cue, routine, reward, friction, identity, and feedback-loop habit analysis.", [input_field("scores", "Dimension scores", "textarea", "cue_clarity=3;routine_feasibility=3;reward_strength=3;friction_reduction=3;identity_alignment=4;feedback_loop=3")], ["habit_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("motivation-reinforcement-learning-tool", "Motivation, Reinforcement, and Learning Tool", "Behavioral Science & Psychology", "Motivation, Reinforcement, and Learning", "motivation_learning", "python/numpy", "Intrinsic motivation, reinforcement schedule, competence feedback, autonomy, and mastery progress.", [input_field("scores", "Dimension scores", "textarea", "intrinsic_motivation=4;extrinsic_support=3;reinforcement_schedule=3;competence_feedback=3;autonomy=4;mastery_progress=3")], ["motivation_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("choice-architecture-nudging-tool", "Choice Architecture and Nudging Tool", "Behavioral Science & Psychology", "Choice Architecture and Nudging", "choice_architecture", "python/numpy", "Default design, salience, friction, transparency, agency, and equity analysis for ethical nudging.", [input_field("scores", "Dimension scores", "textarea", "default_design=3;salience=3;friction=2;transparency=4;user_agency=4;equity=3")], ["choice_profile"], ["guided", "analyst", "expert"], "ethics_review_required"),
    ToolSpec("social-norms-influence-tool", "Social Norms and Behavioral Influence Tool", "Behavioral Science & Psychology", "Social Norms and Behavioral Influence", "social_norms", "python/numpy", "Descriptive norms, injunctive norms, reference groups, visibility, trust, and backfire risk.", [input_field("scores", "Dimension scores", "textarea", "descriptive_norms=3;injunctive_norms=3;reference_group_fit=3;visibility=3;trust=3;backfire_risk_inverse=3")], ["norm_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("behavioral-public-policy-tool", "Behavioral Public Policy Tool", "Behavioral Science & Psychology", "Behavioral Public Policy", "behavioral_public_policy", "python/numpy", "Behavioral public-policy evaluation across evidence, equity, transparency, feasibility, and evaluation.", [input_field("scores", "Dimension scores", "textarea", "problem_definition=4;evidence_base=3;distributional_equity=4;consent_transparency=4;administrative_feasibility=3;evaluation_plan=3")], ["policy_profile"], ["guided", "analyst", "expert"], "professional_review_required"),
    ToolSpec("behavioral-research-methods-tool", "Behavioral Research Methods Tool", "Behavioral Science & Psychology", "Behavioral Research Methods", "behavioral_methods", "python/numpy", "Construct validity, sampling, reliability, experimental design, confounding control, and replicability.", [input_field("scores", "Dimension scores", "textarea", "construct_validity=3;sampling=3;measurement_reliability=3;experimental_design=3;confounding_control=3;replicability=3")], ["methods_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("ethics-behavioral-intervention-tool", "Ethics of Behavioral Intervention Tool", "Behavioral Science & Psychology", "Ethics of Behavioral Intervention", "behavioral_ethics", "python/numpy", "Autonomy, beneficence, nonmaleficence, justice, transparency, and contestability safeguards.", [input_field("scores", "Dimension scores", "textarea", "autonomy=4;beneficence=4;nonmaleficence=4;justice=3;transparency=4;contestability=3")], ["ethics_profile"], ["guided", "analyst", "expert"], "ethics_review_required"),
    ToolSpec("moral-psychology-tool", "Moral Psychology Tool", "Psychology", "Moral Psychology", "moral_psychology", "python/numpy", "Moral foundations, empathy, fairness, authority, liberty, harm/care, and institutional judgment analysis.", [input_field("scores", "Dimension scores", "textarea", "harm_care=4;fairness=4;loyalty=3;authority=2;sanctity=2;liberty=4;empathy=4")], ["moral_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("knowledge-architecture-tool", "Knowledge Architecture Tool", "Thinking", "Knowledge Architecture", "knowledge_architecture", "python/numpy", "Taxonomy, navigation, metadata, source traceability, learning pathways, and governance analysis.", [input_field("scores", "Dimension scores", "textarea", "taxonomy=4;navigation=3;metadata=3;source_traceability=4;learning_pathways=3;governance=3")], ["architecture_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("design-thinking-tool", "Design Thinking Tool", "Thinking", "Design Thinking", "design_thinking", "python/numpy", "Empathy, problem framing, ideation, prototyping, testing, and iteration analysis.", [input_field("scores", "Dimension scores", "textarea", "empathy=3;problem_framing=4;ideation=4;prototyping=3;testing=3;iteration=3")], ["design_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("mathematical-thinking-tool", "Mathematical Thinking Tool", "Thinking", "Mathematical Thinking", "mathematical_thinking", "python/numpy", "Abstraction, formalization, proof logic, model fit, edge cases, and interpretation.", [input_field("scores", "Dimension scores", "textarea", "abstraction=4;formalization=3;proof_logic=3;model_fit=3;edge_cases=4;interpretation=4")], ["math_thinking_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("systems-thinking-tool", "Systems Thinking Tool", "Thinking", "Systems Thinking", "systems_thinking", "python/numpy", "Boundaries, stocks, flows, feedback loops, delays, leverage points, emergence, and unintended consequences.", [input_field("scores", "Dimension scores", "textarea", "boundaries=4;stocks_flows=3;feedback_loops=4;delays=3;leverage_points=3;emergence=3;unintended_consequences=4")], ["systems_profile", "pdf_report"], ["guided", "analyst", "expert"]),
    ToolSpec("algorithms-computational-reasoning-tool", "Algorithms and Computational Reasoning Tool", "Thinking", "Algorithms & Computational Reasoning", "computational_reasoning", "python/numpy", "Problem formalization, data structures, complexity, correctness, testing, and accountability.", [input_field("scores", "Dimension scores", "textarea", "problem_formalization=4;data_structures=3;complexity=3;correctness=4;testing=3;accountability=4")], ["computational_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("resilience-thinking-tool", "Resilience Thinking Tool", "Thinking", "Resilience Thinking", "resilience_thinking", "python/numpy", "Exposure, sensitivity, adaptive capacity, redundancy, learning, recovery, and transformability.", [input_field("scores", "Dimension scores", "textarea", "exposure=4;sensitivity_inverse=3;adaptive_capacity=3;redundancy=3;learning=4;recovery=3;transformability=3")], ["resilience_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("futures-thinking-tool", "Futures Thinking Tool", "Thinking", "Futures Thinking", "futures_thinking", "python/numpy", "Drivers, uncertainties, scenarios, early signals, robust options, and adaptation pathways.", [input_field("scores", "Dimension scores", "textarea", "drivers=4;uncertainties=4;scenarios=3;early_signals=3;robust_options=3;adaptation_pathways=3")], ["futures_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("strategic-ideation-tool", "Strategic Ideation Tool", "Problem Solving", "Strategic Ideation", "strategic_ideation", "python/numpy", "Problem clarity, option diversity, constraints, differentiation, feasibility, and learning value.", [input_field("scores", "Dimension scores", "textarea", "problem_clarity=4;option_diversity=4;constraint_awareness=3;differentiation=4;feasibility=3;learning_value=4")], ["strategy_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("beauty-aesthetics-meaning-tool", "Beauty, Aesthetics, and Meaning Tool", "Meaning", "Beauty, Aesthetics, and Meaning", "aesthetics_meaning", "python/numpy + AI-ready", "Form, pattern, harmony, symbolic depth, emotional resonance, and transcendence analysis.", [input_field("scores", "Dimension scores", "textarea", "form=4;pattern=4;harmony=3;symbolic_depth=4;emotional_resonance=4;transcendence=3")], ["meaning_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("aesthetics-philosophy-art-tool", "Aesthetics and Philosophy of Art Tool", "Meaning", "Aesthetics and the Philosophy of Art", "philosophy_art", "python/numpy + AI-ready", "Representation, expression, formal structure, interpretive openness, historical context, and judgment.", [input_field("scores", "Dimension scores", "textarea", "representation=3;expression=4;formalist_structure=4;interpretive_openness=4;historical_context=3;judgment=3")], ["art_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("mathematics-art-music-pattern-tool", "Mathematics, Art, Music, and Pattern Tool", "Meaning", "Mathematics, Art, Music, and Pattern", "math_art_music_pattern", "python/numpy", "Symmetry, ratio, recursion, rhythm, variation, and emergent pattern analysis.", [input_field("scores", "Dimension scores", "textarea", "symmetry=4;ratio=4;recursion=3;rhythm=4;variation=3;emergent_pattern=4")], ["pattern_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("symbolism-style-cultural-meaning-tool", "Symbolism, Style, and Cultural Meaning Tool", "Meaning", "Symbolism, Style, and Cultural Meaning", "symbolism_style", "python/numpy + AI-ready", "Symbol density, style coherence, cultural context, ritual association, memory, and ambiguity.", [input_field("scores", "Dimension scores", "textarea", "symbol_density=4;style_coherence=3;cultural_context=4;ritual_association=3;memory=4;ambiguity=3")], ["symbolism_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("creative-form-composition-interpretation-tool", "Creative Form, Composition, and Interpretation Tool", "Meaning", "Creative Form, Composition, and Interpretation", "creative_form", "python/numpy + AI-ready", "Structure, tension, contrast, unity, movement, and interpretive depth analysis.", [input_field("scores", "Dimension scores", "textarea", "structure=4;tension=3;contrast=4;unity=3;movement=3;interpretive_depth=4")], ["composition_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("story-myth-meaning-tool", "Story, Myth, and Meaning Tool", "Meaning", "Story, Myth, and Meaning", "story_myth_meaning", "python/numpy + AI-ready", "Mythic structure, ritual depth, archetypal motif, memory, suffering/hope, and sacred order.", [input_field("scores", "Dimension scores", "textarea", "mythic_structure=4;ritual_depth=3;archetypal_motif=4;memory=4;suffering_hope=3;sacred_order=3")], ["myth_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("systems-modeling-tool", "Systems Modeling Tool", "Systems Modeling", "Systems Modeling", "systems_modeling", "python/numpy", "Boundary definition, variable quality, causal structure, feedback representation, calibration, validation, and scenario design.", [input_field("scores", "Dimension scores", "textarea", "boundary_definition=4;variable_quality=3;causal_structure=4;feedback_representation=3;data_calibration=3;validation=3;scenario_design=4")], ["modeling_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("predictive-modeling-tool", "Predictive Analytics", "Predictive Modeling", "predictive_modeling", "predictive_modeling", "python/numpy", "Target definition, feature quality, training data, validation design, calibration, uncertainty, and deployment monitoring.", [input_field("scores", "Dimension scores", "textarea", "target_definition=4;feature_quality=3;training_data=3;validation_design=4;calibration=3;uncertainty=3;deployment_monitoring=3")], ["predictive_readiness_profile"], ["guided", "analyst", "expert"]),
    ToolSpec("limits-to-growth-system-dynamics-tool", "Limits to Growth System Dynamics Tool", "Systems Modeling", "Limits to Growth", "limits_to_growth", "python/numpy", "Simplified stocks, flows, feedback, resource depletion, pollution, overshoot, and collapse-risk scenario modeling.", [input_field("inputs", "Inputs", "textarea", "population=1.0;capital=1.0;resources=1.0;pollution=0.05;birth_rate=0.025;death_rate=0.01;investment_rate=0.04;depletion_rate=0.015;pollution_rate=0.02;years=80")], ["system_dynamics_curve", "pdf_report"], ["guided", "analyst", "expert"], "professional_review_required"),

]

TOOL_BY_ID = {t.id: t for t in TOOLS}

def list_tools(domain: str | None = None, topic: str | None = None, limit: int | None = None) -> list[dict]:
    items = TOOLS
    if domain:
        d = domain.lower()
        items = [t for t in items if d in t.domain.lower()]
    if topic:
        q = topic.lower().replace('-', ' ')
        items = [t for t in items if q in (t.topic + ' ' + t.domain + ' ' + t.description + ' ' + t.family).lower()]
    data = [asdict(t) for t in items]
    if limit:
        data = data[:limit]
    return data

def get_tool(tool_id: str) -> dict | None:
    t = TOOL_BY_ID.get(tool_id)
    return asdict(t) if t else None

def search_tools(query: str, limit: int = 6) -> list[dict]:
    q = (query or '').lower()
    scored = []
    for t in TOOLS:
        blob = ' '.join([t.id, t.title, t.domain, t.topic, t.family, t.description, ' '.join(t.graph_types)]).lower()
        score = sum(2 if token in t.title.lower() else 1 for token in q.split() if token in blob)
        if score:
            scored.append((score, t))
    scored.sort(key=lambda x: (-x[0], x[1].title))
    return [asdict(t) for _, t in scored[:limit]] or [asdict(t) for t in TOOLS[:limit]]
